name: PHP Composer

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Composer validate
      run: composer validate

    - name: Cache Composer cache
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: composer-cache-php${{ matrix.php }}

    - name: Composer install
      run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader
    - name: Run test suite
      run: composer ci
